con actions tercera

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -12,7 +12,20 @@ jobs:
 
       - name: Descargar código
         uses: actions/checkout@v4
+      - name: Comprobar secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "ERROR: DOCKER_USERNAME está vacío"
+            exit 1
+          fi
 
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "ERROR: DOCKER_PASSWORD está vacío"
+            exit 1
+          fi
+
+          echo "DOCKER_USERNAME está configurado"
+          echo "DOCKER_PASSWORD está configurado"
       - name: Iniciar sesión en Docker Hub
         uses: docker/login-action@v3
         with:
